CMAKE_MINIMUM_REQUIRED(VERSION 3.10)
PROJECT(main)
SET(BF_VERSION_MAJOR 2)
SET(BF_VERSION_MINOR 1)
#SET(CMAKE_BUILD_TYPE "DEBUG")
#SET(CMAKE_C_FLAGS_DEBUG "-g")

CONFIGURE_FILE (
	"${PROJECT_SOURCE_DIR}/config.h.in"
	"${PROJECT_SOURCE_DIR}/config.h")
AUX_SOURCE_DIRECTORY(. DIR_SRCS)
ADD_EXECUTABLE(bf ${DIR_SRCS})
